require:
  - rubocop-rspec
  - rubocop-rails
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - vendor/**/*
    - bin/**/*
    - db/**/*
    - deps/**/*
    - node_modules/**/*
Layout/IndentationStyle:
  Enabled: true
Layout/IndentationWidth:
  Width: 2
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/ClassLength:
  Max: 150
  Exclude:
    - app/controllers/**/*
Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - engines/**/config/**/*
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/app.rb
    - config/**/*
    - app/models/request.rb
    - db/**/*
    - app/admin/**/*
Metrics/MethodLength:
  CountAsOne: ["array", "heredoc", "method_call", "hash"]
  Exclude:
    - db/**/*
  Max: 25
Style/IfUnlessModifier:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/BlockComments:
  Exclude:
    - "spec/**/*"
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: "with_fixed_indentation"
Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: "consistent"
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
  AllowMultilineFinalElement: true
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "config.ru"
    - "config/initializers/*"
    - "config/application.rb"
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LeadingCommentSpace:
  Enabled: false
Style/SymbolArray:
  MinSize: 4
Style/QuotedSymbols:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Metrics/BlockNesting:
  Exclude:
    - "config/initializers/*"
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/RequireParentheses:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/ExampleLength:
  Max: 10
  CountAsOne: ["array", "heredoc", "hash"]
Rails/ReversibleMigration:
  Enabled: true
Layout/CaseIndentation:
  EnforcedStyle: end
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/ApplicationController:
  Exclude:
    - app/controllers/v1/**/*
Metrics/AbcSize:
  Exclude:
    - app/controllers/**/*
Rails/SkipsModelValidations:
  AllowedMethods:
    - "touch"
RSpec/InstanceVariable:
  Exclude:
    - spec/e2e/**/*
Rails/I18nLocaleTexts:
  # reenable when we localize
  Enabled: false
