name: Run linter

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.4
    steps:
      - uses: actions/checkout@v1
      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: lint
        run: bundle exec rubocop
