name: Run linter

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: bundler
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: lint
        run: bundle exec rubocop
