name: Run linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.4
    steps:
      - uses: actions/checkout@v1
      - name: Gem cache
        id: cache-bundle
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundler
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: lint
        run: bundle exec rubocop
